version: "3.9"

services:
  redis:
    image: redis:7.2
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data


    # kaldırılabilir ama alttaki backend.depends_on.redis.condition: service_healthy kısmını da kaldırman gerekebilir. bağlılar çünkü
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 30
    # Geliştirirken dışarıdan redis-cli ile bağlanman gerekmiyorsa port açma
    # ports:
    #   - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - REDIS_HOST=redis   # container'dan container'a erişimde servis adı
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}  # prod'da Secrets ile ekle
    depends_on: # healthcheck kaldırılırsa bu koşul anlamsız kalır.
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: infra/Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - backend

    # restart: unless-stopped


volumes:
  redis-data:

    
