version: "3.9"

services:
  redis:
    image: redis:7.2
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 30
    # Geliştirirken dışarıdan redis-cli ile bağlanman gerekmiyorsa port açma
    # ports:
    #   - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - REDIS_HOST=redis   # container'dan container'a erişimde servis adı
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=${REDIS_PASSWORD}  # prod'da Secrets ile ekle
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped


volumes:
  redis-data:

    
